name: Sync labels

on: [label]

jobs:
  labels:
    name: synchronize labels between repos
    runs-on: ubuntu-latest
    steps:
      - name: sync labels between repos
        uses: EndBug/label-sync@v2
        with:
          source-repo: 18F/methods
